import React from 'react';
import { Link } from 'react-router-dom';
import { Search, Bell, AlertTriangle, CalendarDays, Clock, Menu, Calculator, Shield, FileText, TrendingUp, Users, Briefcase, BarChart3, PieChart, Building2, MoreVertical, CheckCircle, UserRound, Check, Headphones } from 'lucide-react';
import { LineChart, Line, ResponsiveContainer, PieChart as DonutChart, Pie, Cell, AreaChart, Area, XAxis, YAxis } from 'recharts';

const gold = '#f4c76b';
const gold2 = '#c99a45';
const text = '#e8ded0';
const line = 'rgba(244,199,107,.22)';
const spark = [{v:14},{v:24},{v:31},{v:36},{v:24},{v:15},{v:20},{v:16},{v:32},{v:26},{v:22}];
const redSpark = [{v:12},{v:20},{v:24},{v:16},{v:9},{v:14},{v:10},{v:22},{v:30},{v:23}];
const savings = [{m:'Dic',v:6200},{m:'Ene',v:10800},{m:'Feb',v:12300},{m:'Mar',v:16800},{m:'Abr',v:14500},{m:'May',v:28450}];

function Panel({ children, className = '', glow = false }) {
  return <div className={`rounded-lg ${className}`} style={{ background: glow ? 'radial-gradient(circle at top right, rgba(244,199,107,.28), transparent 40%), linear-gradient(180deg,#111,#050505)' : 'linear-gradient(180deg,#0b0b0a,#030303)', border: glow ? '1px solid rgba(244,199,107,.75)' : `1px solid ${line}`, boxShadow: glow ? '0 0 28px rgba(244,199,107,.24)' : 'inset 0 1px 0 rgba(255,255,255,.03)' }}>{children}</div>;
}

function Stat({ title, value, change, bad, glow }) {
  const data = bad ? redSpark : spark;
  return <Panel glow={glow} className="p-4 h-[130px]"><div className="uppercase text-[13px] leading-5" style={{color:gold}}>{title}</div><div className="mt-2 text-3xl font-semibold" style={{color:glow?'#e6b16e':text}}>{value}</div><div className="flex justify-between text-xs"><span>Este mes</span><span style={{color:bad?'#ff3434':'#55d14b'}}>{change}</span></div><div className="h-9 mt-2"><ResponsiveContainer><LineChart data={data}><Line type="monotone" dataKey="v" stroke={bad?'#ff3434':gold} strokeWidth={2} dot={{r:2,fill:bad?'#ff3434':gold,strokeWidth:0}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></Panel>;
}

function Risk({ value }) {
  const color = value === 'Alto' ? '#ff4a3d' : value === 'Medio' ? '#ffc44d' : '#69d64b';
  return <span className="px-3 py-1 rounded-md text-xs" style={{color,border:`1px solid ${color}`,background:'rgba(255,255,255,.03)'}}>{value}</span>;
}

const modules = [
  ['/erp','ERP','Sistema integral',Calculator],['/audit','Auditoría','Control y riesgos',Shield],['/documents','Documentos','Gestión documental',FileText],['/finance','Finanzas','Análisis financiero',TrendingUp],['/crm','CRM','Clientes y ventas',Users],['/hr','Recursos Humanos','Talento humano',Briefcase],['/operations','Operaciones','Procesos',BarChart3],['/predictive','Análisis Predictivo','IA y datos',PieChart]
];
const rows = [
  ['Logística Andina S.A.C.','Logística','Medio','15/05/2025 08:45 AM'],['Inversiones Globales S.A.','Financiero','Alto','15/05/2025 07:30 AM'],['Manufacturas del Sur S.A.','Manufactura','Bajo','14/05/2025 05:20 PM'],['Servicios Integrales SAC','Servicios','Medio','14/05/2025 05:10 PM'],['Comercializadora Norte EIRL','Comercio','Alto','14/05/2025 04:05 PM']
];
const activity = [[FileText,'Análisis completados','15 hoy · Total: 356 este mes','Hace 10 min','#55d14b'],[FileText,'Documentos cargados','Estudios Q1.pdf por Juan Pérez','Hace 25 min','#55d14b'],[AlertTriangle,'Alerta emitida: Riesgo Tributario','Logística Andina S.A.C.','Hace 1 hora','#ff3434'],[Calculator,'Reporte generado','Resumen Mayo 2025 por Sistema IA','Hace 2 horas',gold],[Check,'Validación documental completada','Inversiones Globales S.A.','Hace 3 horas',gold],[UserRound,'Usuario conectado','Juan Pérez inició sesión','Hace 4 horas','#777']];

export default function GemaillaDashboard(){
  return <div className="min-h-screen overflow-hidden" style={{background:'#050505',color:text}}>
    <div className="border-b px-6 py-3" style={{borderColor:'rgba(244,199,107,.14)'}}><div className="flex items-center justify-between gap-5"><div className="flex flex-1 items-center gap-5"><Menu className="h-7 w-7"/><div className="relative w-[535px] max-w-full"><Search className="absolute left-4 top-1/2 h-6 w-6 -translate-y-1/2"/><input className="h-12 w-full rounded-lg border bg-black/40 pl-14 pr-4 text-base outline-none" style={{borderColor:line,color:text}} placeholder="Buscar empresas, documentos, análisis..."/></div></div><div className="flex items-center gap-5 text-sm"><div className="relative"><Bell className="h-6 w-6"/><span className="absolute -right-2 -top-2 flex h-5 w-5 items-center justify-center rounded-full bg-red-600 text-[11px] text-white">3</span></div><div className="flex items-center gap-2 border-l pl-5" style={{borderColor:line}}><AlertTriangle className="h-5 w-5" style={{color:gold}}/>2 Alertas críticas</div><div className="border-l pl-5" style={{borderColor:line}}>GEMAILLA IA</div><span style={{color:'#55d14b'}}>● Conectado</span><div className="flex h-10 w-10 items-center justify-center rounded-full text-lg font-bold" style={{background:`linear-gradient(135deg,${gold},${gold2})`,color:'#1c1307'}}>G</div></div></div></div>
    <div className="px-7 py-5"><div className="flex items-start justify-between"><div><h1 className="text-3xl font-semibold">¡Bienvenido de vuelta!</h1><p className="mt-1 text-lg">Aquí tienes el resumen de tu actividad empresarial</p></div><Panel className="w-[285px] px-5 py-3"><div className="flex items-center gap-4 border-b pb-3" style={{borderColor:line}}><CalendarDays className="h-6 w-6" style={{color:gold}}/>15 de mayo de 2025</div><div className="mt-3 flex items-center gap-4"><Clock className="h-6 w-6" style={{color:gold}}/>09:15 AM</div></Panel></div>
      <h2 className="mb-3 mt-4 text-lg uppercase tracking-wide" style={{color:gold}}>Accesos Directos</h2><div className="grid grid-cols-2 gap-4 md:grid-cols-4 xl:grid-cols-8">{modules.map(([path,label,sub,Icon])=><Link key={path} to={path}><Panel className="flex h-[124px] flex-col items-center justify-center px-3 text-center transition-transform hover:-translate-y-1"><Icon className="mb-3 h-9 w-9" style={{color:gold}}/><div className="text-lg leading-5">{label}</div><div className="mt-1 text-sm opacity-70">{sub}</div></Panel></Link>)}</div>
      <div className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-6"><Stat title="Empresas Activas" value="24" change="+18%"/><Stat title="Documentos Procesados" value="1,248" change="+24%"/><Stat title="Análisis IA" value="356" change="+12%"/><Stat title="Alertas Activas" value="7" change="-5%" bad/><Stat title="Tareas en Proceso" value="15" change="-7%" bad/><Stat title="Ahorro Estimado" value="$28,450" change="+32%" glow/></div>
      <div className="mt-5 grid grid-cols-1 gap-4 xl:grid-cols-[1.25fr_.75fr_.98fr]"><Panel className="p-4"><div className="mb-4 flex items-center justify-between"><h3 className="text-lg uppercase" style={{color:gold}}>Empresas</h3><div className="flex gap-3"><Link to="/companies" className="text-sm underline" style={{color:gold}}>Ver todas</Link><Link to="/companies" className="rounded-md px-4 py-2 text-sm font-semibold" style={{background:`linear-gradient(135deg,${gold},${gold2})`,color:'#050505'}}>+ Nueva</Link></div></div><table className="w-full text-sm"><thead><tr className="opacity-70"><th className="px-2 py-3 text-left font-normal">EMPRESA</th><th className="px-2 py-3 text-left font-normal">SECTOR</th><th className="px-2 py-3 text-left font-normal">ESTADO</th><th className="px-2 py-3 text-left font-normal">RIESGO</th><th className="px-2 py-3 text-left font-normal">ÚLTIMO ANÁLISIS</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r[0]} style={{borderTop:'1px solid rgba(244,199,107,.12)'}}><td className="px-2 py-3"><span className="mr-3 inline-flex h-7 w-7 items-center justify-center rounded-full border" style={{borderColor:'rgba(244,199,107,.35)'}}><Building2 className="h-4 w-4"/></span>{r[0]}</td><td>{r[1]}</td><td style={{color:'#68d84e'}}>Activa</td><td><Risk value={r[2]}/></td><td className="opacity-70">{r[3]}</td><td><MoreVertical className="h-5 w-5"/></td></tr>)}</tbody></table></Panel>
      <div className="space-y-4"><Panel className="p-4"><h3 className="mb-4 text-lg uppercase" style={{color:gold}}>Análisis en Tiempo Real</h3><div className="grid grid-cols-[130px_1fr] items-center gap-4"><div className="relative h-[130px]"><ResponsiveContainer><DonutChart><Pie data={[{value:92},{value:8}]} innerRadius={48} outerRadius={63} dataKey="value" startAngle={90} endAngle={-270}><Cell fill={gold}/><Cell fill="rgba(244,199,107,.18)"/></Pie></DonutChart></ResponsiveContainer><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-3xl font-semibold">92%</span><span className="text-xs">Completado</span></div></div><div className="space-y-3 text-sm"><div><CheckCircle className="mr-2 inline h-5 w-5 text-green-500"/>Saturación de datos<br/><span className="ml-7 text-green-500">Completo</span></div><div><CheckCircle className="mr-2 inline h-5 w-5 text-green-500"/>Validación documental<br/><span className="ml-7 text-green-500">Completo</span></div><div><Clock className="mr-2 inline h-5 w-5" style={{color:gold}}/>Análisis financiero<br/><span className="ml-7" style={{color:gold}}>En progreso</span></div></div></div><div className="mt-3 border-t pt-3 text-sm" style={{borderColor:line}}><Clock className="mr-2 inline h-4 w-4"/> Tiempo: 00:21:24</div></Panel><Panel className="p-4"><div className="mb-2 flex justify-between"><h3 className="text-lg uppercase" style={{color:gold}}>Histórico de Ahorro Estimado</h3></div><div className="h-[145px]"><ResponsiveContainer><AreaChart data={savings}><XAxis dataKey="m" tick={{fill:'rgba(232,222,208,.72)',fontSize:12}}/><YAxis tickFormatter={v=>`$${v/1000}K`} tick={{fill:'rgba(232,222,208,.72)',fontSize:12}}/><Area type="monotone" dataKey="v" stroke={gold} fill="rgba(244,199,107,.18)" strokeWidth={2} dot={{r:4,fill:gold,strokeWidth:0}} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></Panel></div>
      <Panel className="p-4"><div className="mb-3 flex justify-between"><h3 className="text-lg uppercase" style={{color:gold}}>Actividad Reciente</h3><Link to="/activity" className="text-sm underline" style={{color:gold}}>Ver todas</Link></div><div className="relative pl-7"><div className="absolute bottom-7 left-[11px] top-3 w-px bg-white/35"/>{activity.map(([Icon,a,b,c,col])=><div key={a} className="relative grid grid-cols-[32px_1fr_auto] gap-3 border-b py-3 last:border-b-0" style={{borderColor:'rgba(244,199,107,.12)'}}><span className="absolute -left-[29px] top-5 h-4 w-4 rounded-full border-2 bg-black" style={{borderColor:col}}/><Icon className="h-7 w-7" style={{color:col}}/><div><div>{a}</div><div className="text-sm opacity-60">{b}</div></div><div className="text-xs opacity-70">● {c}</div></div>)}</div></Panel></div></div>
    <footer className="flex items-center justify-between border-t px-7 py-4 text-sm" style={{borderColor:'rgba(244,199,107,.1)',color:'rgba(232,222,208,.55)'}}><span>© 2025 GEMAILLA IA. Todos los derechos reservados.</span><div className="flex gap-8"><span>Última sync: Hoy, 09:15 AM</span><span className="flex gap-2"><Headphones className="h-5 w-5"/>Soporte 24/7</span></div></footer>
  </div>;
}
